version: '3'
services:
  react-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - app/frontend/node_modules
      - .:/app/frontend
  react-frontend-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - app/frontend/node_modules
      - .:/app/frontend
    command: ["npm", "run", "test"]
